spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/testbase?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Bizzic7567
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    my_secret: banana

  sql:
    init:
      mode: always
      continue-on-error: true